name: Testing Continuously Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.4'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest coverage

      - name: Run unit tests and generate coverage report
        run: |
          coverage run -m pytest -v units/bank_test.py
          coverage report -m

  system_tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-describe coverage
      
      - name: Run system tests and generate coverage report
        run: |
          coverage run -m pytest -v system_tests/test_squirrel_server_api.py
          coverage report -m
  behave_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install system dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip google-chrome-stable

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave selenium
      
      - name: Link ChromeDriver to PATH
        run: |
          sudo ln -s /usr/bin/google-chrome /usr/local/bin/chrome
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Run Behave Tests
        run: |
          behave behave_tests/features
        continue-on-error: true

      - name: Upload screenshots as artifacts
        if: failure() 
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: "behave_tests/screenshots/*.png" 